openapi: 3.1.0

info:
  contact:
    email: techsupport@example.com
    name: Example API Support
    url: http://exampleurl.com/contact
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: Quarkus Social API
  version: ${properties.appVersion}
tags:
  - name: Users
    description: Users operations.
  - name: Posts
    description: Operations related to posts
  - name: Followers
    description: Operations related to followers
paths:
  /users:
    get:
      responses:
        "200":
          description: OK
      summary: List All Users
      tags:
        - Users
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUserRequestDTO"
        required: true
      responses:
        "200":
          description: OK
      summary: Create User
      tags:
        - Users
  /users/{id}:
    put:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUserRequestDTO"
        required: true
      responses:
        "200":
          description: OK
      summary: Update User
      tags:
        - Users
    delete:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
      summary: Delete User
      tags:
        - Users
  /users/{userId}/followers:
    delete:
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: followerId
          in: query
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
      summary: Unfollow User
      tags:
        - Followers
    get:
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
      summary: Get User Followers
      tags:
        - Followers
    put:
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FollowerRequestDTO"
        required: true
      responses:
        "200":
          description: OK
      summary: Follow User
      tags:
        - Followers
  /users/{userId}/posts:
    post:
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePostRequestDTO"
        required: true
      responses:
        "200":
          description: OK
      summary: Save Post
      tags:
        - Posts
    get:
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: followerId
          in: header
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
      summary: List Posts
      tags:
        - Posts
components:
  schemas:
    CreatePostRequestDTO:
      type: object
      required:
        - text
      properties:
        text:
          type: string
          pattern: \S
    CreateUserRequestDTO:
      type: object
      required:
        - name
        - age
      properties:
        name:
          type: string
          pattern: \S
        age:
          type: integer
          format: int32
    FollowerRequestDTO:
      type: object
      properties:
        followerId:
          type: integer
          format: int64