CREATE DATABASE quakus_social;

CREATE TABLE "POSTS" (
	id bigserial NOT NULL PRIMARY KEY,
    post_text VARCHAR(150) NOT NULL,
	dateTime TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	user_id BIGINT NOT NULL REFERENCES users(id)
);